#!/usr/bin/env node

// Paint by Numbers Generator CLI
// This is the entry point for the CLI application

const path = require('path');
const scriptDir = __dirname;
const mainPath = path.join(scriptDir, 'src-cli', 'main.js');

require(mainPath);
